### ISSUE TITLE
Twitter Embeds Broken

### ISSUE THREAD

**Issue by mattrothenberg** [wrav/oembed#68]
I noticed on my site that all of my Twitter embeds stopped working when adding embeds to entries. No matter how I format the Twitter URL, the server throws a 500 when trying to preview the entry (and hence when rendering the entry on the front-end)

Could this be related to https://github.com/oscarotero/Embed/issues/421?

I'm on version 1.3.4

**Comment by reganlawton** [comment]
If its a local 500 eror can you provide some logs to help me pinpiint the possible issue?

**Comment by mattrothenberg** [comment]
@reganlawton Sorry, forgot to add the stack trace 👇 

```
2020-12-22 08:14:52 [-][1][jj0rhei4j08etjrbda2htvnjof][error][yii\base\Exception] Embed\Exceptions\InvalidUrlException: Invalid url 'https://twitter.com/mattrothenberg/status/1339925295676203010' (Status code 400) in /home/forge/passivehouseaccelerator.com/vendor/embed/embed/src/Embed.php:142
Stack trace:
#0 /home/forge/passivehouseaccelerator.com/vendor/embed/embed/src/Embed.php(81): Embed\Embed::process(Object(Embed\Http\Url), Array, Object(Embed\Http\CurlDispatcher))
#1 /home/forge/passivehouseaccelerator.com/vendor/wrav/oembed/src/services/OembedService.php(47): Embed\Embed::create(Object(Embed\Http\Url), Array)
#2 /home/forge/passivehouseaccelerator.com/vendor/wrav/oembed/src/models/OembedModel.php(141): wrav\oembed\services\OembedService->embed('https://twitter...', Array)
#3 /home/forge/passivehouseaccelerator.com/vendor/wrav/oembed/src/models/OembedModel.php(150): wrav\oembed\models\OembedModel->embed(Array)
#4 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Extension/CoreExtension.php(1499): wrav\oembed\models\OembedModel->media()
#5 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(wrav\oembed\models\OembedModel), 'media', Array, 'any', false, false)
#6 /home/forge/passivehouseaccelerator.com/storage/runtime/compiled_templates/85/8541778fc26d58a6b7cc19a001ac8d092df6f00514ba9ddb5d388d98a7fdf1fd.php(38): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(wrav\oembed\models\OembedModel), 'media', Array)
#7 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_b0b38b90e2cd095203e5a025eed05d031c21f523fff96186da9e3e5f93e4f6da->doDisplay(Array, Array)
#8 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#10 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#11 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/View.php(466): Twig\TemplateWrapper->render(Array)
#12 /home/forge/passivehouseaccelerator.com/vendor/trendyminds/molecule/src/services/MoleculeService.php(50): craft\web\View->renderString('{% set provider...', Array)
#13 /home/forge/passivehouseaccelerator.com/vendor/trendyminds/molecule/src/variables/MoleculeVariable.php(26): trendyminds\molecule\services\MoleculeService->getComponent('BlockEmbed', Array)
#14 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Extension/CoreExtension.php(1499): trendyminds\molecule\variables\MoleculeVariable->get('BlockEmbed', Array)
#15 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(trendyminds\molecule\variables\MoleculeVariable), 'get', Array, 'method', false, false)
#16 /home/forge/passivehouseaccelerator.com/storage/runtime/compiled_templates/82/8281ea8f8747c18a2199a892d34bd5a953ff129d29dff18eecdf9495015a7bd5.php(135): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(trendyminds\molecule\variables\MoleculeVariable), 'get', Array, 'method')
#17 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_42e558d64c2e7d81e3a1ef61fe57b5e0d1e1b68bb37dac83463d6e15ad16ffc8->doDisplay(Array, Array)
#18 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /home/forge/passivehouseaccelerator.com/storage/runtime/compiled_templates/2e/2eb60c199489da3b0e7e958cb1ec0350d4f9e7383dda110df47b5e4d855c0f88.php(194): Twig\Template->display(Array)
#20 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(184): __TwigTemplate_3d7c18f2d194a7f1cd57c9454f41fed4088cf3216f97e9552dd12c36a50f7f40->block_body(Array, Array)
#21 /home/forge/passivehouseaccelerator.com/storage/runtime/compiled_templates/ef/efa34b8bbef729a9da4cc9acaaff24e4c099d77b169b07ca1fbf3431465e3504.php(107): Twig\Template->displayBlock('body', Array, Array)
#22 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_1e4e36c4daf16bf29d0feff1e80caad26d91e0d85e4d70148a8f67fd667566ba->doDisplay(Array, Array)
#23 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /home/forge/passivehouseaccelerator.com/storage/runtime/compiled_templates/2e/2eb60c199489da3b0e7e958cb1ec0350d4f9e7383dda110df47b5e4d855c0f88.php(49): Twig\Template->display(Array, Array)
#25 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_3d7c18f2d194a7f1cd57c9454f41fed4088cf3216f97e9552dd12c36a50f7f40->doDisplay(Array, Array)
#26 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#27 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#28 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#29 /home/forge/passivehouseaccelerator.com/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#30 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('articles/_entry', Array)
#31 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('articles/_entry', Array)
#32 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('articles/_entry', Array)
#33 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('articles/_entry', Array)
#34 [internal function]: craft\controllers\TemplatesController->actionRender('articles/_entry', Array)
#35 /home/forge/passivehouseaccelerator.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#36 /home/forge/passivehouseaccelerator.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#37 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#38 /home/forge/passivehouseaccelerator.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#39 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#40 /home/forge/passivehouseaccelerator.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#41 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/Application.php(162): yii\web\Application->handleRequest(Object(craft\web\Request))
#42 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/controllers/PreviewController.php(146): craft\web\Application->handleRequest(Object(craft\web\Request), true)
#43 [internal function]: craft\controllers\PreviewController->actionPreview('craft\\elements\\...', 245692, 1, 2768, NULL)
#44 /home/forge/passivehouseaccelerator.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#45 /home/forge/passivehouseaccelerator.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#46 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('preview', Array)
#47 /home/forge/passivehouseaccelerator.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('preview', Array)
#48 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('preview/preview', Array)
#49 /home/forge/passivehouseaccelerator.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('preview/preview', Array)
#50 /home/forge/passivehouseaccelerator.com/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#51 /home/forge/passivehouseaccelerator.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#52 /home/forge/passivehouseaccelerator.com/web/index.php(21): yii\base\Application->run()
#53 {main}

**Comment by reganlawton** [comment]
Can I also get the twitter URL so I can test and debug please and I think that'll be enough to debug the issue for now.

**Comment by reganlawton** [comment]
So can I get the version of craft and oembed your using and if you can get the version or embed/embed too that's be great I'll try match the exact versions

**Comment by mattrothenberg** [comment]
@reganlawton Sure thing. FWIW, it sounds eerily similar to that upstream issue I linked to in my PR.

Craft: 3.3.20.1
Embed: 3.4.8
