### ISSUE TITLE
Version 1.3.7: Class 'wrav\oembed\models\Json' not found

### ISSUE THREAD

**Issue by sanderpotjer** [wrav/oembed#77]
```
Error: Class 'wrav\oembed\models\Json' not found in /vendor/wrav/oembed/src/models/OembedModel.php:109
Stack trace:
#0 /vendor/wrav/oembed/src/models/OembedModel.php(136): wrav\oembed\models\OembedModel->getUrl()
#1 /vendor/twig/twig/src/Extension/CoreExtension.php(1511): wrav\oembed\models\OembedModel->render()
#2 /vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(wrav\oembed\models\OembedModel), 'render', Array, 'any', false, false)
#3 /storage/runtime/compiled_templates/ee/eefd69491a06284434d7afd46192a74126c510d595686e15d2ac3db57606a2cc.php(265): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(wrav\oembed\models\OembedModel), 'render', Array)
```

So missing namespace `use craft\helpers\Json;`

**Comment by reganlawton** [comment]
@sanderpotjer THis is resolved in v1.3.8 during to a namespacing issue
